name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"

    steps:
    - name: Checkout Código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Dependencias Linux
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev lld libffi-dev python3-setuptools
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Compilar com Buildozer
      run: |
        yes | buildozer android debug
      env:
        ACCEPT_SDK_LICENSE: "y"

    - name: Guardar Ficheiro APK
      uses: actions/upload-artifact@v4
      with:
        name: Ponto-APK
        path: bin/*.apk
