name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Código
      uses: actions/checkout@v4

    - name: Compilar APK via Docker Isolado
      # Usa a imagem oficial e blindada do Buildozer onde o Python e o Android SDK nunca entram em conflito
      uses: ArtemGovorov/buildozer-action@v1
      with:
        buildozer_version: stable
        command: android debug

    - name: Enviar Ficheiro APK Final
      uses: actions/upload-artifact@v4
      with:
        name: Ponto-APK
        path: bin/*.apk
